import {
  Column,
  CreateDateColumn,
  Entity,
  OneToMany,
  PrimaryColumn,
  UpdateDateColumn,
  type Relation,
} from 'typeorm';
import { PERSISTED_INVOICE_STATUSES, type PersistedInvoiceStatus } from '../domain/invoice-status';
import { InvoiceCustomerColumns } from './invoice-customer.embedded';
import { InvoiceItemEntity } from './invoice-item.entity';

/**
 * The only uniqueness rule on invoice numbers: a unique index on upper(invoice_number), so INV-001 and inv-001 are the
 * same number (and two INV-001 trivially are).
 */
export const INVOICE_NUMBER_CASE_INSENSITIVE_INDEX = 'invoices_invoice_number_upper_uq';
export const INVOICE_CREATED_BY_FOREIGN_KEY = 'invoices_created_by_fk';

/**
 * Persistence model of an invoice. Money columns are numeric(14,2) and typed `string`: node-postgres returns NUMERIC
 * as text precisely so no precision is lost (the mapper turns them into decimals). `date` columns are plain
 * `YYYY-MM-DD` strings (see typeorm-options.ts). The schema itself is defined by the SQL migration.
 */
@Entity({ name: 'invoices' })
export class InvoiceEntity {
  /** Generated by the backend (crypto.randomUUID) so the id is known before the INSERT. */
  @PrimaryColumn({ name: 'invoice_id', type: 'uuid' })
  id: string;

  @Column({ name: 'invoice_number', type: 'varchar', length: 50 })
  invoiceNumber: string;

  @Column({ name: 'invoice_reference', type: 'varchar', length: 100, nullable: true })
  invoiceReference: string | null;

  @Column({ name: 'invoice_date', type: 'date' })
  invoiceDate: string;

  @Column({ name: 'due_date', type: 'date' })
  dueDate: string;

  @Column({ type: 'char', length: 3 })
  currency: string;

  @Column({ name: 'currency_symbol', type: 'varchar', length: 8 })
  currencySymbol: string;

  @Column({ type: 'varchar', length: 500, nullable: true })
  description: string | null;

  @Column({
    type: 'enum',
    enum: PERSISTED_INVOICE_STATUSES,
    enumName: 'invoice_status',
    default: 'Draft',
  })
  status: PersistedInvoiceStatus;

  @Column(() => InvoiceCustomerColumns, { prefix: false })
  customer: InvoiceCustomerColumns;

  // The schema's DEFAULT 10 on tax_rate and DEFAULT 0 on total_discount mirror DEFAULT_TAX_RATE / DEFAULT_DISCOUNT
  // (domain) for rows written outside the API; the API always writes both values itself.
  @Column({ name: 'tax_rate', type: 'numeric', precision: 5, scale: 2 })
  taxRate: string;

  @Column({ name: 'invoice_sub_total', type: 'numeric', precision: 14, scale: 2 })
  invoiceSubTotal: string;

  @Column({ name: 'total_tax', type: 'numeric', precision: 14, scale: 2 })
  totalTax: string;

  @Column({ name: 'total_discount', type: 'numeric', precision: 14, scale: 2 })
  totalDiscount: string;

  @Column({ name: 'total_amount', type: 'numeric', precision: 14, scale: 2 })
  totalAmount: string;

  @Column({ name: 'total_paid', type: 'numeric', precision: 14, scale: 2 })
  totalPaid: string;

  @Column({ name: 'balance_amount', type: 'numeric', precision: 14, scale: 2 })
  balanceAmount: string;

  @Column({ name: 'created_by', type: 'uuid' })
  createdBy: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;

  @OneToMany(() => InvoiceItemEntity, (item) => item.invoice)
  items: Relation<InvoiceItemEntity>[];
}
